package com.predictthesky.app;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.preference.PreferenceManager;

public class LauncherActivity extends Activity
{
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        // Set the current theme as generated by the applications onCreate method
        setTheme(App.currentTheme);

        super.onCreate(savedInstanceState);

        // Get the preferences data
        SharedPreferences data = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());

        // Set up the preferred activity transitions, simple fade by default
        App.transitionInAnimation = data.getInt("transitionInAnim", android.R.anim.fade_in);
        App.transitionOutAnimation = data.getInt("transitionOutAnim", android.R.anim.fade_out);

        // Check preferences to see if we need to initialise preferences and get initial location
        // Default return is false as, in case of error, we initialise by default.
        Boolean doInit = data.getBoolean(getString(R.string.preferencekey_initapp), false);

        Intent intent;

        if (doInit)
        {
            intent = new Intent(getApplicationContext(), InitActivity.class);
        }
        else
        {
            intent = new Intent(getApplicationContext(), MainActivity.class);
        }

        startActivity(intent);

        // Subsequent Activity started, finish up here and transition using the previously
        // set transitions.
        finish();
        overridePendingTransition(App.transitionInAnimation, App.transitionOutAnimation);
    }
}
